Broker working with controller and monitor. Interactive client and ro…
bigsea-ufcg/bigsea-manager pull request #13
Opened 2017-10-09 19:24 UTC by robertonscjr

…utes to logs added

2017-10-10 17:44 UTC, armstrongmsg requested changes

2017-10-10 17:44 UTC, armstrongmsg commented on application_manager/service/api/v10.py
> +def _replace(string):
maybe rename to "_remove_newline"?

2017-10-10 17:44 UTC, armstrongmsg commented on application_manager/plugins/sahara/plugin.py
>              if current_job_time > 3600:
This if block should be removed. It does not make sense to kill an application that takes more than one hour to finish.

2017-10-10 17:44 UTC, armstrongmsg commented on application_manager/service/api/v10.py
> +    log = open("logs/sahara_plugin.log", "r")
I believe this log file is only used in Spark Sahara plugin. How about OpenStack Generic?

2017-10-10 17:44 UTC, armstrongmsg commented on application_manager/service/api/v10.py
> +    str_log = map(_replace, log.readlines())
What if the log file is too big?

2017-10-10 17:44 UTC, armstrongmsg commented on application_manager/plugins/sahara/plugin.py
> +            f = open("logs/sahara_plugin.log", "w")
What if many applications are running at the same time? Maybe we should use different log files for each application. Something like "sahara_plugin_{app_id}.log".

2017-10-13 13:34 UTC, armstrongmsg requested changes

2017-10-13 13:34 UTC, armstrongmsg commented on application_manager/plugins/sahara/plugin.py
>      def _mkdir(self, path):
Why not use this instead? https://docs.python.org/2/library/os.html#os.mkdir

2017-10-16 11:38 UTC, tellesnobrega commented on application_manager/plugins/sahara/plugin.py
>              if current_job_time > 3600:
I think we could add a timeout but it should be bigger.

2017-10-16 11:40 UTC, tellesnobrega commented on application_manager/service/api/v10.py
> +def _replace(string):
agreed

2017-10-16 11:50 UTC, tellesnobrega commented on application_manager/plugins/sahara/plugin.py
> +        plugin_log.log("%s | Creating directories (CLUSTER)" %
porque essa mudança?

2017-10-19 13:28 UTC, robertonscjr commented on application_manager/plugins/sahara/plugin.py
>              if current_job_time > 3600:
Should this be parametrized by the client?

2017-10-19 13:33 UTC, armstrongmsg commented on application_manager/plugins/sahara/plugin.py
>              if current_job_time > 3600:
Yes, I think it is a good solution to add the timeout as parameter.

2017-10-19 15:30 UTC, armstrongmsg requested changes

2017-10-19 15:30 UTC, armstrongmsg commented on application_manager/utils/remote.py
> +
Remove this blank line

2017-10-19 15:30 UTC, armstrongmsg commented on application_manager/utils/remote.py
> +    command = ('ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i %(key_path)s ubuntu@%(remote)s %(command)s' %
Isn't "StrictHostKeyChecking no" enough? Why do you need to pass /dev/null as known_hosts file?

2017-10-19 15:30 UTC, armstrongmsg commented on application_manager/api/v10.py
> +    return u.render(api.std_log(app_id))
How about the standard error output? Why isn't there a "stderr_log" option?

2017-10-19 17:02 UTC, robertonscjr commented on application_manager/api/v10.py
> +    return u.render(api.std_log(app_id))
'std_log' provides the standard outputs of a Spark submission: stderr and stdout.

2017-10-19 17:11 UTC, robertonscjr commented on application_manager/utils/remote.py
> +    command = ('ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i %(key_path)s ubuntu@%(remote)s %(command)s' %
'UserKnownHostsFile=/dev/null' ignores the "man-in-the-middle" message.

2017-10-19 17:15 UTC, armstrongmsg commented on application_manager/utils/remote.py
> +    command = ('ssh -o "StrictHostKeyChecking no" -o "UserKnownHostsFile=/dev/null" -i %(key_path)s ubuntu@%(remote)s %(command)s' %
ok

2017-10-19 17:50 UTC, iurygregory commented on application_manager/api/v10.py
> +    return u.render(api.std_log(app_id))
std_log it's fine since is for both

2017-10-19 18:14 UTC, robertonscjr commented on application_manager/utils/remote.py
> +
Removed.

2017-10-19 18:15 UTC, merged