Added method which return amount of vcpu by nodegroup and added the u…
bigsea-ufcg/bigsea-manager pull request #21
Opened 2017-12-12 17:00 UTC by robertonscjr

…sage of optimizer in Spark-Sahara plugin.

2017-12-12 18:01 UTC, robertonscjr commented
When application name is **bulma**, the field **days** should exists in submission of client. If name isn't **bulma**, check if exists **cluster size** and use it. 
In some (two) cases the Spark-Sahara will throw an exception: 
-> application name is **bulma** and the field **days** doesn't exists. 
-> the amount of **cores** is _less equal than zero._ and doesn't exists **cluster_size** parameter.

2017-12-12 18:02 UTC, armstrongmsg approved these changes

2017-12-12 18:09 UTC, igornatanael requested changes

2017-12-12 18:09 UTC, igornatanael commented on application_manager/plugins/sahara/plugin.py
> +                req_cluster_size = ((cores / cores_per_slave) +
use math.ceil()

2017-12-12 18:09 UTC, igornatanael commented on application_manager/plugins/sahara/plugin.py
> +                    raise ex.ConfigurationError()
Please add a message for this exception

2017-12-12 18:09 UTC, igornatanael commented on application_manager/plugins/sahara/plugin.py
> +                    raise ex.ConfigurationError()
same here

2017-12-12 19:01 UTC, betobetodev commented on application_manager/plugins/sahara/plugin.py
> +                    raise ex.ConfigurationError()
Done @igornatanael .

2017-12-12 19:01 UTC, robertonscjr commented on application_manager/plugins/sahara/plugin.py
> +                req_cluster_size = ((cores / cores_per_slave) +
Done @igornatanael .

2017-12-12 19:01 UTC, betobetodev commented on application_manager/plugins/sahara/plugin.py
> +                    raise ex.ConfigurationError()
Done @igornatanael .

2017-12-13 11:24 UTC, igornatanael approved these changes

2017-12-13 11:24 UTC, merged