Refactoring code to make it more usable, readable and understandable
bigsea-ufcg/bigsea-manager pull request #25
Opened 2018-05-02 18:28 UTC by robertonscjr

2018-05-14 19:31 UTC, igornatanael requested changes
some suggestions and change requests

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +To more info, see [details.md](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/docs/details.md)
the path for the details.md must point to the master branch. so you have to use https://github.com/bigsea-ufcg/bigsea-manager/tree/master/docs/details.md

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +The broker is implemented following a **plugin architecture**, providing flexibility to add or remove plugins when necessary.
suggestion: change "providing flexibility to add or remove plugins when necessary" to "providing flexibility to customize your deployment using only the plugins you need, avoiding to include unnecessary dependencies (from others plugins) to your deploy environment."

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +See [plugin-development.md](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/docs/plugin-development.md).
the same comment about the branch in the file path

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +* Python 2.7 or Python 3.5
does it really work well with python 3?
I don't think so

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +* Linux packages: python-dev and python-pip
I think that there are others, as ssl and some packages that you have to install to have python-dev working properly.

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +To **apt** distros, you can use [pre-install.sh](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/tools/pre-install.sh) to install the requirements.
the same comment about the branch in the file path

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +First of all, install **git**. After, you just need to clone the [Broker repository](https://github.com/bigsea-ufcg/bigsea-manager.git) in your machine.
I don't this it is necessary this step about install git. Too much dump.

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +You can find a template in [config-example.md](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/docs/config-example.md).
same comment about the branch in the file path

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +$ tox -e venv -- broker
the pattern decided is that we will always use ./run.sh, even if this file contains only the tox commands. 
it is a strategy to keep all the components easy to run and install and with the same command for all of they.

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +Endpoints is avaliable on [restapi-endpoints.md](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/docs/restapi-endpoints.md) documentation.
"Endpoints is" > "Endpoints are"

2018-05-14 19:31 UTC, igornatanael commented on README.md
> +Endpoints is avaliable on [restapi-endpoints.md](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/docs/restapi-endpoints.md) documentation.
same comment about the branch in the file path

2018-05-14 19:31 UTC, igornatanael commented on broker/utils/framework/monitor.py
> +        'plugin_info': info_plugin,
also change the value "info_plugin" to "plugin_info"

2018-05-14 19:31 UTC, igornatanael commented on docs/asperathos-workflow.md
> +![Flow](https://github.com/bigsea-ufcg/bigsea-manager/blob/refactor/docs/flow.png)
same comment about the branch in the file path

2018-05-14 19:31 UTC, igornatanael commented on docs/config-example.md
> +# Config example
maybe would be better to move the plugins specific information to each plugin description. 
imagine the day we have 100 plugins, so this example will have 100 fields? you can add only two plugins fields here called "plugin-#" and make like this:

`[plugin-1]
p1_info1 = lorem
p1_info2 = ipsum

[plugin-2]
p2_info1 = lorem_ipsum
p2_info2 = ipsum_lorem
`

2018-05-14 19:31 UTC, igornatanael commented on docs/installation.md
> +First of all, install **git**. After, you just need to clone the [Broker repository](https://github.com/bigsea-ufcg/bigsea-manager.git) in your machine.
unnecessary git install step (again)

2018-05-14 19:31 UTC, igornatanael commented on docs/installation.md
> +To **apt** distros, you can use [pre-install.sh](https://github.com/bigsea-ufcg/bigsea-manager/tree/refactor/tools/pre-install.sh) to install the requirements.
again, change branch on the file path link

2018-05-14 19:31 UTC, igornatanael commented on tools/pre-install.sh
> +#!/bin/bash
move this script to root

2018-05-14 19:31 UTC, igornatanael commented on tools/run.sh
> +#!/bin/bash
move this script to root

2018-05-16 14:04 UTC, robertonscjr commented
@igornatanael check the changes, please.

2018-05-17 18:09 UTC, igornatanael approved these changes

2018-05-17 18:09 UTC, merged